---
plugins:
  - tag
  - user
  - security
  - db
  - crisp
  - errors

database: 
  host: 
  username: 
  password: 
  db: 

logger:
  logTo: nowhere
#        db/file/nowhere

  database: 					#database connection for the logger
    host: 
    username: 
    password: 
    db: 
  
env:
  dev:
    debug: 3
    database: 
      host: 
      username: 
      password: 
      db: 

#  prod:
#    debug: 0
#    database: 
#      host: <production host>
#      username: <username>
#      password: <password>
#      db: <database>